name: napari-spatialdata
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - ipykernel
  - pip:
    - napari-spatialdata[all]
    - paramiko
    - sshfs==2024.9.0
    - vedo
    - napari-animation
    - ipywidgets
